# Harvest pipeline defaults tuned for stability and low fragmentation

# Frame sampling & detection
stride: 1
det_size: [960, 960]
face_conf_th: 0.30
person_conf_th: 0.10
face_in_track_iou: 0.10
allow_face_center: false
dilate_track_px: 0.25
temporal_iou_tolerance: 3

# Harvest sampling
samples_per_track: 12
samples_min: 4
samples_max: 16
min_gap_frames: 8
min_area_frac: 0.003
min_area_px: null
min_sharpness_laplacian: 20.0
sharpness_pctile: 5
min_frontalness: 0.10
frontal_pctile: 50
min_frontal_picks: 2
profile_asymmetry_thresh: 0.35
quality_weights: [0.5, 0.2, 0.3]
target_area_frac: 0.02
debug_rejections: true
multi_face_per_track_guard: true
multi_face_tiebreak: quality
fallback_head_pct: 0.4

# Identity guard and stitching
identity_guard: true
identity_split: true
identity_sim_threshold: 0.62
identity_min_picks: 3
identity_guard_stride: 6
identity_guard_consecutive: 3
identity_guard_cosine_reject: 0.35
reindex_harvest_tracks: true
stitch_identities: true
stitch_sim: 0.45
stitch_gap_ms: 8000
stitch_min_iou: 0.10

# Tracker pacing
min_track_frames: 12
new_track_min_frames: 3
max_new_tracks_per_sec: 2

# Track gap handling
max_gap_ms: 300
min_run_ms: 600

# Identity voting & persistence
similarity_th: 0.78
vote_decay: 0.99
flip_tolerance: 0.30

# Identity change detection
identity_split_min_frames: 5
identity_change_margin: 0.05
identity_split_enabled: true
embed_every_n: 2

# Progress reporting defaults
progress_fallback_frames: 500

# Sample-based label fallback (uses harvested selected_samples)
sample_label_fallback_enabled: true
sample_label_min_votes: 1
sample_label_min_score: 0.45
sample_label_window_frames: 45
